site_name: Bjorn
site_description: Бот Telegram для студенческих групп
site_author: Даниил Голубев
site_url: https://github.com/dadyarri/bjorn
theme:
    name: material
    language: ru
    palette:
            primary: teal
            accent: teal
    font:
            text: Roboto
            code: Fira Code
    icon:
            logo: fontawesome/solid/robot
            repo: fontawesome/brands/github

repo_name: dadyarri/bjorn
repo_url: https://github.com/dadyarri/bjorn

copyright: Copyright &copy; 2020 Даниил Голубев

markdown_extensions:
        - admonition
        - codehilite:
                guess_lang: false
        - toc:
                permalink: true
        - pymdownx.arithmatex
        - pymdownx.betterem:
                smart_enable: all
        - pymdownx.caret
        - pymdownx.critic
        - pymdownx.details
        - pymdownx.emoji:
                emoji_index: !!python/name:pymdownx.emoji.twemoji
                emoji_generator: !!python/name:pymdownx.emoji.to_svg
        - pymdownx.inlinehilite
        - pymdownx.magiclink
        - pymdownx.mark
        - pymdownx.smartsymbols
        - pymdownx.superfences
        - pymdownx.tasklist:
                custom_checkbox: true
        - pymdownx.tabbed
        - pymdownx.tilde
plugins:
    - search
    - macros
    - mkdocstrings:
        default_handler: python
        handlers:
            python:
                rendering:
                    show_source: true
        watch:
            - bot

nav:
        - Главная: index.md
        - Функционал:
                - Призыв: functions/call.md
                - Рассылки: functions/mailings.md
                - Финансы: functions/finances.md
                - Расписание: functions/schedule.md
                - Настройки: functions/preferences.md
        - Разработка:
                - Кодекс поведения участника: dev/code-of-conduct.md
                - Соглашения о наименовании: dev/code-of-naming.md
                - Соглашение о стиле кода: dev/codestyle.md
                - Внесение вклада: dev/contributing.md
                - Адаптация: dev/adopt.md
                - Зависимости: dev/requirements.md
        - Модули:
                - Bot:
                        - Клавиатуры: modules/bot/keyboards.md
                        - Реплики: modules/bot/replicas.md
                        - Утилиты: modules/bot/utils.md
                