name: Build docs

# Controls when the action will run. Triggers the workflow on push
# event but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout master
      uses: actions/checkout@v2

    - name: Installing requirements
      run: |
        pip install -U pip --user
        pip install -r dev_requirements.txt --user
        pip install -r requirements.txt --user
        export PYTHONPATH=..
        cd docs
        mkdocs gh-deploy
