name: Build docs

# Controls when the action will run. Triggers the workflow on push
# event but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout master
      uses: actions/checkout@v2
    - name: Updating PATH
      run: PATH=$PATH:/home/runner/.local/bin

    - name: Installing requirements
      run: |
        python3 -m pip install setuptools
        python3 -m pip install -U pip
        python3 -m pip install -r dev_requirements.txt
        
    - name: Building docs
      run: |
        export PYTHONPATH=..
        cd docs
        mkdocs gh-deploy
